### ISSUE TITLE
This browser does not seem to support crypto.getRandomValues()

### ISSUE THREAD

**Issue by sharqawiDev** [thenativeweb/uuidv4#126]
I've imported the library in my react native project and whenever I try to use it, it does not work!
I got this error message:
![photo_2020-02-26_18-20-51](https://user-images.githubusercontent.com/27745505/75359124-fc6c1f00-58c4-11ea-80b3-b0b81f05f72a.jpg)

any help please

**Comment by goloroden** [comment]
This is probably a problem with how React Native and / or the browser provides access to the APIs (or maybe the suggested API is actually missing).

Unfortunately, we do not have any experience with React Native, and also unfortunately we don't have the capacity to look into this, as we only need this for Node.js ourselves.

If you want to track this thing down, and find the cause for this, and if you may want to submit a PR, we'll be happy to adopt it 😊
