### ISSUE TITLE
Receving build error with 6.0.5 in expo

### ISSUE THREAD

**Issue by Fleuv** [thenativeweb/uuidv4#127]
Seems like the additions of uuid v5 crashed compatibility with expo and maybe even react-native, the error message:

> The package at "node_modules/uuidv4/node_modules/uuid/v5.js" attempted to import the Node standard library module "util". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq/#can-i-use-nodejs-packages-with-expo
> Building JavaScript bundle: error

**This error occurred after I updated from 6.0.2 to version 6.0.5.**

**Comment by goloroden** [comment]
This is probably a problem with how React Native and / or the browser provides access to the APIs (or in this case the suggested API is actually missing).

Unfortunately, we do not have any experience with React Native, and also unfortunately we don't have the capacity to look into this, as we only need this for Node.js ourselves.

If you want to track this thing down, and find the cause for this, and if you may want to submit a PR, we'll be happy to adopt it 😊
