### ISSUE TITLE
uuidv4 requires uuid "3.3.3", which doesn't exist

### ISSUE THREAD

**Issue by bamtheboozle** [thenativeweb/uuidv4#14]
Pretty much title. When running with `yarn install`, yarn can't find uuid v3.3.3 and asks to downgrade to 3.3.2, which is fine.

Running with `npm install` though it fails, because npm can't find uuid3.3.3 which is listed as a dependency of uuidv4.

**Comment by goloroden** [comment]
Correct me if I’m wrong, but npm lists a 3.3.3: https://www.npmjs.com/package/uuid

**Comment by goloroden** [comment]
PS: Are you using an npm proxy (which maybe is not up-to-date)?

**Comment by bamtheboozle** [comment]
Interesting, I am not currently using a proxy and neither is a colleague that's currently working from home.

**Comment by goloroden** [comment]
For our build server, things work. Strange ... 😐

However, I assume that there is an infrastructure problem on your side. Hence I’m going to close this as not reproducible.
