### ISSUE TITLE
uuidv4 module not found

### ISSUE THREAD

**Issue by neonshobhit** [thenativeweb/uuidv4#156]
const { uuid } = require('uuidv4');
 throws error: 'MODULE_NOT_FOUND' if installed at latest version npm i uuidv4
but works fine with npm i uuidv4@6.0.7

**Comment by goloroden** [comment]
Can you provide a sample repository?

For me, it works with the latest version, so unfortunately I can't reproduce it 🤔

**Comment by taranttini** [comment]
Error: No valid exports main found for 'node_modules\uuid' ???

**Comment by goloroden** [comment]
@taranttini I don't know what your problem is, since it is quite hard to get from

> Error: No valid exports main found for 'node_modules\uuid' ???

what the cause is, despite multiple question marks (as if this would be the most obvious thing in the world).

As already stated before:

> Can you provide a sample repository?
>
> For me, it works with the latest version, so unfortunately I can't reproduce it 🤔

As long as you don't come up with a sample that we can reproduce on our side, we won't be able to help you, sorry 😐

**Comment by taranttini** [comment]
in uuid version 7.0.3 has 
in all dist file (v1.js, v3.js, v4.js, v5.js)
```
exports.default = _default;
module.exports = exports.default; 
```

in uuid version 8.0.0

only
```
exports.default = _default;
```

maybe this is the problem to  
`Error: No valid exports main found for 'MY_FILE_PATH\node_modules\uuid'`

But thanks, I solve my problem

**Comment by goloroden** [comment]
Once again – can you please provide a repository with a small example that helps to reproduce this issue?

**Comment by goloroden** [comment]
PS: For me, in a newly created and empty directory, when I run

```shell
$ npm install uuidv4
```

and then add an `app.js` file with the following contents

```javascript
const { uuid } = require('uuidv4');

console.log(uuid());
```

and I then run this using

```shell
$ node app.js
```

a UUID is shown. So I can't reproduce this issue, sorry. And just providing a single line of error message doesn't help at all to be able to find the cause of your problems…

**Comment by taranttini** [comment]
https://github.com/taranttini/uuid_problem

**Comment by goloroden** [comment]
@taranttini Thanks for the sample repository, and sorry for the dumb question – your two sample projects don't even use this module at all, instead they directly refer to `uuid` (please note this is the repository for `uuidv4`!).

As we aren't the creators of `uuid`, we don't provide support for it directly.
