### ISSUE TITLE
Only way to import is destructuring { uuid }

### ISSUE THREAD

**Issue by louisnk** [thenativeweb/uuidv4#158]
Just switched over for the 90% size reduction from the plain UUID package, so thank you for giving us a great, slim package to use!

May be an edge case here, but the places my project uses `uuid` it is often putting that into an object by doing something like:

```
...
const uuid = uuidv4(); 
return { uuid, data };
```

With the current export signature of this module I either have to do some hacky things or change everywhere that I use uuids to nolonger use `uuid` as my own variable.

See [PR here](https://github.com/thenativeweb/uuidv4/pull/159)

**Comment by goloroden** [comment]
Hi @louisnk 👋 

Thanks for your nice feedback and your keen words 😊

Regarding your issue… If you are using JavaScript, you could simply write your `require` like this:

```javascript
const { uuid: uuidv4 } = require('uuidv4');
```

In TypeScript (or JavaScript ESM modules) you could use:

```typescript
import { uuid as uuidv4 } from 'uuidv4';
```

Both work out of the box, are (IMHO) no "hacky things", and you can use `uuid` as your very own variable – all without adding another export to the module.

Wouldn't this work for you (especially given that this can be done using a simple search/replace if you already have required or imported the `uuidv4` module anywhere)?
