### ISSUE TITLE
uuidv4 won't work on react-native

### ISSUE THREAD

**Issue by wmonecke** [thenativeweb/uuidv4#168]
### issue

`uuidv4` stops working on release builds of react-native.
The error occurs because `crypto.getRandomValues` is not provided out of the box in react-native in release mode.
When in debug mode it works since Chrome debugger comes with `crypto.getRandomValues`.

Reference issue: https://github.com/uuidjs/uuid/issues/375

**Comment by goloroden** [comment]
@wmonecke Thanks for the hint 😊 

Unfortunately, as you also already laid out, this is an upstream issue. So until they have fixed this, I think your best bet is to use an older version of the `uuidv4` module.

**Comment by wmonecke** [comment]
Yes downgrading to v3.0.0 fixes this.
Thank you!
