### ISSUE TITLE
Differences with `uuid`?

### ISSUE THREAD

**Issue by ctavan** [thenativeweb/uuidv4#182]
Hi! I'm one of the maintainers of the [`uuid`](https://github.com/uuidjs/uuid) module which is used as a dependency under the hood of this module.

I was made aware of this module due to a bug report (https://github.com/uuidjs/uuid/issues/488) which ended up in the wrong repository.

With the upcoming `uuid@8.3.0` release we will be adding `parse`/`stringify`/`validate`/`version` methods as well as a `NIL` constant. So I was wondering what the remaining differences to this module would then still be? (Maybe JSON Schema?)

I just realized that many of the recent bug reports in this repo were actually just manifestations of upstream bugs, so maybe it would reduce overall maintenance burden if we simply merged the two modules together? BTW this has happened a few years ago already when we merged `node-uuid` and `uuid` into one module.

In any case I just wanted to let you know that we're always open for contributions at https://github.com/uuidjs/uuid If there is no interest from your end to consolidate the efforts then please just close this issue.

**Comment by goloroden** [comment]
Hi @ctavan 👋 

Thanks for getting into contact!

You're right, the modules got more and more similar over time (of course, we do just a small subset of what you do). Originally we had our own implementation, but eventually switched to use `uuid`, which degrades `uuidv4` to be a simple convenience wrapper.

It's actually questionable if it's worth to keep it as a standalone module, if you now are going to introduce all these things. And the JSON schemas could actually easily be added via a PR.

I think we'll discuss this internally, but I just wanted to say thanks for reaching out, and it's definitely a good idea to talk about this one 😊

Once we've talked about it, I will get back to you!

**Comment by goloroden** [comment]
@ctavan It's me again (yes, slightly faster than expected 😉) …

We all agree that it doesn't make sense to have both, so we will phase out `uuidv4` and mark it as deprecated soon, and point people to `uuid` instead. And regarding the JSON schemas, we will submit a PR.

It probably won't happen today or tomorrow, but expect to hear back from us soon …

Again, thanks for opening up this topic!

**Comment by ctavan** [comment]
Thanks for reacting so quickly. Then let's discuss the remaining topics over at the `uuid` repo 😄

**Comment by ctavan** [comment]
Oh: And BTW we are still waiting for feedback on the `8.3.0-beta.0` release, it will take a couple of days until we make the release. So there's really no rush.
