### ISSUE TITLE
Update for Doc

### ISSUE THREAD

**Issue by abdulmoizlakhani** [thenativeweb/uuidv4#215]
Hello,
Please update the following lines on the docs.

Now working: `import { uuid } from 'uuidv4';`
Working: `import uuid from 'uuidv4';`

Thanks

![uuid_prob](https://user-images.githubusercontent.com/25384728/94365141-eedf7780-00e7-11eb-9996-c569973dacdd.PNG)
![uuid_prob_02](https://user-images.githubusercontent.com/25384728/94365142-f010a480-00e7-11eb-8bad-a0344880f1a0.PNG)

**Comment by goloroden** [comment]
Hi @abdulmoizlakhani 👋 

With the current version of `uuidv4`, the described syntax

```typescript
import { uuid } from 'uuidv4';
```

works perfectly fine.

Hence I'm going to close this issue.
