### ISSUE TITLE
6.2.4 error: Error: Unable to resolve module `util` from `node_modules/uuidv4/build/lib/uuidv4.js`

### ISSUE THREAD

**Issue by approached** [thenativeweb/uuidv4#223]
Hi@all,

I have a error with the version 6.2.4:
```
error: Error: Unable to resolve module `util` from `node_modules/uuidv4/build/lib/uuidv4.js`: util could not be found within the project.
```

I switched back to 6.1.1, that works fine.

**Comment by goloroden** [comment]
Do you have a repository with a simple example to reproduce the issue?

**Comment by approached** [comment]
It's not possible to share. It's a _react native_ project.

**Comment by goloroden** [comment]
Unfortunately, then it’s not reproducible for us, and we don’t support React Native.
