### ISSUE TITLE
uuid.fromString is fundamentally flawed

### ISSUE THREAD

**Issue by AthenasEngineering** [thenativeweb/uuidv4#3]
The function fromString as found here: https://github.com/thenativeweb/uuidv4/blob/master/src/uuidv4.js#L24 is unfortunately fundamentally flawed and not up to RFC specifications.

A UUID v4 is supposed to be a cryptographically random generated UUID. fromString makes that entire specification moot and generates a UUID based of a string by cutting pieces the now deprecated sha1 hash, and due to UUID limitations, it can't use all of its 40 characters, opening up for further collisions.

**Comment by goloroden** [comment]
It's true, this is not according to the spec – it is just a function that we needed internally. It allowed us to create an ID in a deterministic way that at least *looks* like a UUID, but of course isn't one.

Do you have any suggestion how to do this in a better way?

**Comment by AthenasEngineering** [comment]
UUIDv3/5 does more or less what your current function does.  It takes a UUID as a "namespace" and mixes it in with the bytes of the supplied string, then uses the hash function for that particular UUID version and formats it into a UUID string.

UUID v3 uses md5 to accomplish this and UUIDv5 uses sha1. So  it's more or less identical to what you're doing, except it's got namespaces/salting in the mix, and does the proper byte switching for versioning.

Example here: https://github.com/kelektiv/node-uuid/blob/master/lib/v35.js

**Comment by goloroden** [comment]
This is highly interesting, I didn’t know this!

It actually seems to be a pretty good idea to change the function here to a v3 or v5 UUID. We‘ll do this eventuelly.
