### ISSUE TITLE
TypeError: uuid is not a function

### ISSUE THREAD

**Issue by mdodge-ecgrow** [thenativeweb/uuidv4#303]
No idea what I am doing wrong here.  I installed `uuivv4` and it shows up in my package.json under dependencies: ` "uuidv4": "^6.2.6"`.  
So in my NodeJS code, I import it and attempt to use it like so:
```js
import uuid from 'uuidv4';
...
const clientID = uuid();
```
And I get the error: `TypeError: uuid is not a function`

**Comment by mdodge-ecgrow** [comment]
OK, finally figured this out.  I had to use it like this instead: `const clientID = uuid.uuid();`.  Maybe because I imported it instead of requiring it?  Not sure why the syntax is slightly different from the example, but it works!

**Comment by strangedev** [comment]
Hi :wave: 

the `uuid` function is exported as a [named export](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export). If you change your code just slightly, it will work as expected :blush: 

```TypeScript
import { uuid } from 'uuidv4';
...
const clientId = uuid();
```

**Comment by mdodge-ecgrow** [comment]
I had tried that and this is the error I get:
![image](https://user-images.githubusercontent.com/57459547/108535496-04c12500-72a1-11eb-8dcb-c076136fb8ae.png)

**Comment by goloroden** [comment]
Please note that you can not use `import` in TypeScript without TypeScript or without using ESM modules.

To use `require`, you would have to write:

```javascript
const { uuid } = require('uuidv4');
```

However, please note that this package is deprecated anyway, and you should use the `uuid` module instead of.
