### ISSUE TITLE
DeprecationWarning: uuidv4() is deprecated. Use v4() from the uuid module instead.

### ISSUE THREAD

**Issue by BaseMax** [thenativeweb/uuidv4#370]
**Code:**
```
const { uuid } = require('uuidv4')

console.log(uuid)
```

**Output:**
```
[Function: deprecated]
```

Why `deprecated`?

**Comment by goloroden** [comment]
We deprecated this since the `uuid` module is more complete and in the end this module, which started independently, was just a wrapper around the other one – so you can equally well directly use `uuid`.

**Comment by BaseMax** [comment]
```
const { v4: uuidv4 } = require('uuid')
```

Thanks, works;
Done

**Comment by laoshaw** [comment]
for me it has to be `const {v4 as uuidv4| = require('uuid');`

**Comment by Vigneshgvs** [comment]
for es6:
import { v4 as uuidv4 } from 'uuid';
console.log(uuidv4());

**Comment by goldingdamien** [comment]
Are all the same features supported in uuid?
For example:
https://github.com/thenativeweb/uuidv4#getting-a-uuid-from-a-string

**Comment by supunTE** [comment]
uuid:  https://www.npmjs.com/package/uuid
