### ISSUE TITLE
webpack 5 no longer include polyfills

### ISSUE THREAD

**Issue by brianpooe** [thenativeweb/uuidv4#376]
Getting error: 

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }

This is using uuidv4 on nx workspaces.

**Comment by goloroden** [comment]
Thanks for bringing up this issue.

As you can [see here](https://github.com/thenativeweb/uuidv4#please-note), this module is (going to be) deprecated, so we won't fix anything any more.

Please use `uuid` directly.
