### ISSUE TITLE
uuidv4() is deprecated?

### ISSUE THREAD

**Issue by radiorz** [thenativeweb/uuidv4#391]
which packge should i choose?

**Comment by vaiwen** [comment]
take a look 
https://github.com/uuidjs/uuid

1- npm install uuid
2- import { v4 as uuidv4 } from 'uuid';   (ES6 module syntax)
   uuidv4(); // ⇨ '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'

or

2- const { v4: uuidv4 } = require('uuid');  (CommonJS syntax)
   uuidv4(); // ⇨ '1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed'

**Comment by vaiwen** [comment]
> which packge should i choose?

take a look
https://github.com/uuidjs/uuid

```
1- npm install uuid
```


### ES6 module syntax
```
2- import { v4 as uuidv4 } from 'uuid';
   uuidv4(); // ⇨ '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'
```

or

### CommonJS syntax
```
2- const { v4: uuidv4 } = require('uuid');
uuidv4(); // ⇨ '1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed'
```
