### ISSUE TITLE
strange dependencies on npm 

### ISSUE THREAD

**Issue by scenaristeur** [thenativeweb/uuidv4#401]
strange deps : https://www.npmjs.com/package/uuidv4

![image](https://github.com/thenativeweb/uuidv4/assets/4020744/ffe52c5e-1e1f-4b62-bb47-5ae25209581b)

**Comment by goloroden** [comment]
This broken link was a link to a service which showed a badge (similar to the others) telling whether the package's dependencies were up-to-date or not. Apparently, they stopped their service, so one would need to remove these badges from the README.md.

If you send a PR, I will merge it.
