### ISSUE TITLE
Syntax error in regular expression

### ISSUE THREAD

**Issue by robmarshall** [thenativeweb/uuidv4#81]
On IE, the /u modifier is not supported, as discussed here:
https://stackoverflow.com/questions/59102986/uuidv4-js-regular-expression-issue-ie11

I am not sure of the way around this. Any suggestions?

**Comment by yeldiRium** [comment]
Hi Rob,

all our packages are made with the newest Node.js LTS version in mind and we do not try to be compatible with all browsers, especially older ones.

However, if you want to use uuidv4 in a browser-side application, you can use [babel](https://babeljs.io/) in your build process to transpile the code to code that is compatible with older browsers. I haven't specifically used babel with regular expressions containing the `u` flag myself, but I'm confident that babel can get those to work with IE11.

Good luck and kind regards,
yeldiR

**Comment by arthabus** [comment]
this one seem to support IE 11:
https://github.com/uuidjs/uuid#readme
