### ISSUE TITLE
regex does not test 36 chars  length

### ISSUE THREAD

**Issue by salvoravida** [thenativeweb/uuidv4#87]
here is a correct v4 regex 

/^[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12}$/i;

**Comment by goloroden** [comment]
Can you please provide an example of an incorrect input which causes the current regex to pass?

**Comment by goloroden** [comment]
Found a sample for an incorrect input. Added some tests to reproduce the issue, and fixed the implementation.
